update qckcmd

diff --git a/bin/bin/qckcmd b/bin/bin/qckcmd
--- a/bin/bin/qckcmd
+++ b/bin/bin/qckcmd
@@ -1,109 +1,209 @@
-#!/bin/bash
+#!/usr/bin/env perl
+use strict;
+use warnings;
+use feature 'signatures';
+no warnings 'experimental::signatures';
 
-enable -n echo
+use Getopt::Std;
+use File::Slurp qw(read_file write_file);
 
-RCFILE="options.conf"
-declare -A POINTS
+my %QCKCMDS;
+my %REGISTERS;
 
-if [[ -n "${NO_COLOR:-}" ]]; then
-    readonly BOLD=""
-    readonly RED=""
-    readonly GREEN=""
-    readonly YELLOW=""
-    readonly BLUE=""
-    readonly MAGENTA=""
-    readonly RST=""
-else
-    readonly BOLD=$'\e[1m'
-    readonly RED=$'\e[31m'
-    readonly GREEN=$'\e[32m'
-    readonly YELLOW=$'\e[33m'
-    readonly BLUE=$'\e[34m'
-    readonly MAGENTA=$'\e[35m'
-    readonly RST=$'\e[0m'
-fi
+my ($BOLD, $RED, $GREEN, $YELLOW, $BLUE, $MAGENTA, $RST);
+if ($ENV{NO_COLOR}) {
+    ($BOLD, $RED, $GREEN, $YELLOW, $BLUE, $MAGENTA, $RST) = ('') x 7;
+} else {
+    $BOLD    = "\e[1m";
+    $RED     = "\e[31m";
+    $GREEN   = "\e[32m";
+    $YELLOW  = "\e[33m";
+    $BLUE    = "\e[34m";
+    $MAGENTA = "\e[35m";
+    $RST     = "\e[0m";
+}
 
 # Magic to alias stdout to stderr,
 #  to keep everything from clobbing stdout,
 #  but save the file descriptor so it can
 #  be restored on a successful select
-exec 3>&1
-exec 1>&2
+open(my $REAL_STDOUT, '>&', \*STDOUT) or die "Cannot dup STDOUT: $!";
+open(STDOUT, '>&', \*STDERR)          or die "Cannot redirect STDOUT to STDERR: $!";
 
-function usage(){
-echo "${RED}> QuiCK CoMmanDs"
-echo "${RST}"
-echo "    ${BLUE}qckcmd${RST} ${MAGENTA}[options]${RST}"
-echo "        ${YELLOW}-${RST}h        ${YELLOW}:${RST} print this help message"
-echo "        ${YELLOW}-${RST}i ${MAGENTA}<file>${RST} ${YELLOW}:${RST} specify config file"
-echo ""
-echo "Utility to launch pre${YELLOW}-${RST}defined commands quickly"
-echo "by mapping them to characters${YELLOW}.${RST}"
-echo ""
-echo "It could conceptually be called a command bookmark system${YELLOW}.${RST}"
-echo ""
-echo "${BLUE}Qckcmd${RST} has the benefit over regular short${YELLOW}-${RST}cuts that${YELLOW}:${RST}"
-echo "${YELLOW}*${RST} You are echod a list of your short${YELLOW}-${RST}cuts which helps remembering${YELLOW}.${RST}"
-echo "${YELLOW}*${RST} By introducing a leader key${YELLOW},${RST} your terminal${YELLOW}/${RST}shell ${YELLOW}-${RST}especially Bash${YELLOW}-${RST}"
-echo "   won't steal your perfect mnemonic${YELLOW}.${RST}"
-echo ""
-echo "The config file should contain entries separated by newlines${YELLOW}:${RST}"
-echo "    ${MAGENTA}<KEY>${RST}${YELLOW}:${RST} ${MAGENTA}<COMMAND>${RST}"
-echo ""
-echo "${BLUE}Qckcmd${RST} is not supposed to be ran by hand${YELLOW},${RST}"
-echo "instead you are supposed to configure your shell such that ${BLUE}Qckcmd${RST} is bound to a short${YELLOW}-${RST}cut${YELLOW}.${RST}"
-echo "${YELLOW}(${RST}Small${YELLOW})${RST} wrappers for Bash and Fish are vendored to you in the project root${YELLOW}.${RST}"
-echo "The wrappers assume the short${YELLOW}-${RST}cut ${GREEN}\`ctrl+p\`${RST} and the config file ${GREEN}\`~/.qckcmd\`${RST}${YELLOW}.${RST}"
-echo "Note that ${BLUE}qckcmd${RST} does not actually execute commands${YELLOW},${RST} it echos the selected one"
-echo "and the wrappers eval the result${YELLOW}.${RST}"
-echo "This has the benefit that they can modify the shell ${YELLOW}(${RST}e${YELLOW}.${RST}g${YELLOW}.${RST} use ${GREEN}\`source\`${RST}${YELLOW}).${RST}"
-echo ""
-echo "Homepage${YELLOW}:${RST} ${RED}https${RST}${YELLOW}://${RST}${RED}github${RST}${YELLOW}.${RST}${RED}com${RST}${YELLOW}/${RST}${RED}agvxov${RST}${YELLOW}/${RST}${BLUE}qckcmd${RST}"
+sub usage() {
+    print "${RED}> QuiCK CoMmanDs\n";
+    print "${RST}\n";
+    print "    ${BLUE}qckcmd${RST} ${MAGENTA}[options]${RST}\n";
+    print "        ${YELLOW}-${RST}h        ${YELLOW}:${RST} print this help message\n";
+    print "        ${YELLOW}-${RST}i ${MAGENTA}<file>${RST} ${YELLOW}:${RST} specify config file\n";
+    print "        ${YELLOW}-${RST}r ${MAGENTA}<file>${RST} ${YELLOW}:${RST} specify register file\n";
+    print "\n";
+    print "Utility to launch pre${YELLOW}-${RST}defined commands quickly\n";
+    print "by mapping them to characters${YELLOW}.${RST}\n";
+    print "\n";
+    print "It could conceptually be called a command bookmark system${YELLOW}.${RST}\n";
+    print "\n";
+    print "${BLUE}Qckcmd${RST} has the benefit over regular short${YELLOW}-${RST}cuts that${YELLOW}:${RST}\n";
+    print "${YELLOW}*${RST} You are shown a list of your short${YELLOW}-${RST}cuts which helps remembering${YELLOW}.${RST}\n";
+    print "${YELLOW}*${RST} By introducing a leader key${YELLOW},${RST} your terminal${YELLOW}/${RST}shell ${YELLOW}-${RST}especially Bash${YELLOW}-${RST}\n";
+    print "   won${YELLOW}'${RST}t steal your perfect mnemonic${YELLOW}.${RST}\n";
+    print "\n";
+    print "The config file should contain entries separated by newlines${YELLOW}:${RST}\n";
+    print "    ${MAGENTA}<KEY>${RST}${YELLOW}:${RST} ${MAGENTA}<COMMAND>${RST}\n";
+    print "\n";
+    print "${BLUE}Qckcmd${RST} is not supposed to be run by hand${YELLOW},${RST}\n";
+    print "instead you are supposed to configure your shell such that ${BLUE}Qckcmd${RST} is bound to a short${YELLOW}-${RST}cut${YELLOW}.${RST}\n";
+    print "${YELLOW}(${RST}Small${YELLOW})${RST} wrappers for Bash and Fish are vendored to you in the project root${YELLOW}.${RST}\n";
+    print "The wrappers assume the short${YELLOW}-${RST}cut ${GREEN}\`ctrl+p\`${RST} and the config file ${GREEN}\`~/.qckcmd\`${RST}${YELLOW}.${RST}\n";
+    print "Note that ${BLUE}qckcmd${RST} does not actually execute commands${YELLOW},${RST} it prints the selected one\n";
+    print "and the wrappers eval the result${YELLOW}.${RST}\n";
+    print "This has the benefit that they can modify the shell ${YELLOW}(${RST}e${YELLOW}.${RST}g${YELLOW}.${RST} use ${GREEN}\`source\`${RST}${YELLOW}).${RST}\n";
+    print "\n";
+    print "Homepage${YELLOW}:${RST} ${RED}https://github.com/agvxov/qckcmd${RST}\n";
 }
 
-function list_options() {
-	for KEY in "${!POINTS[@]}"; do
-		echo -e "${YELLOW}${BOLD}${KEY}${RST}${BOLD})${RST} ${POINTS[$KEY]}"
-	done
+sub list_options() {
+    for my $key (sort keys %QCKCMDS) {
+        print "${YELLOW}${BOLD}${key}${RST}${BOLD})${RST} $QCKCMDS{$key}\n";
+    }
+    for my $key (sort keys %REGISTERS) {
+        print "${MAGENTA}${BOLD}${key}${RST}${BOLD})${RST} $REGISTERS{$key}\n";
+    }
 }
 
-function read_config() {
-	while IFS= read -r line; do
-		KEY=$(echo "$line" | cut -d ':' -f 1)
-		CMD=$(echo "$line" | cut -d ':' -f 2-)
-		POINTS["$KEY"]="${CMD#"${CMD%%[![:space:]]*}"}"
-	done < "$1"
-
+sub read_config($file) {
+    for my $line (read_file($file, chomp => 1)) {
+        next unless $line =~ /\S/;
+        my ($key, $cmd) = split(/:/, $line, 2);
+        next unless defined $key && defined $cmd;
+        $key =~ s/^\s+|\s+$//g;
+        $cmd =~ s/^\s+//;
+        $QCKCMDS{$key} = $cmd;
+    }
 }
 
-OPTSTR="hi:"
-while getopts "${OPTSTR}" O; do
-	case $O in
-		h) usage && exit ;;
-		i) read_config ${OPTARG} ;;
-		*) echo -e "${RED}Unrecognized option, exiting...${RST}" && exit 1 ;;
-	esac
-done
+sub read_registers($file) {
+    if (! -e $file) {
+        return;
+    }
 
-while true; do
-	list_options
+    for my $line (read_file($file, chomp => 1)) {
+        next unless $line =~ /\S/;
+        my ($key, $cmd) = split(/>/, $line, 2);
+        next unless defined $key && defined $cmd;
+        $key =~ s/^\s+|\s+$//g;
+        $cmd =~ s/^\s+//;
 
-	printf "${RED}> ${RST}"
-	read -n 1 INPUT
-	echo ""
+        if (exists $QCKCMDS{$key}) {
+            warn "Register '$key' would shadow a shortcut. Cowardly refusing to add.\n";
+            next;
+        }
+        $REGISTERS{$key} = $cmd;
+    }
+}
 
-	INPUT="${INPUT#"${INPUT%%[![:space:]]*}"}"
-	if [[ -z "$INPUT" ]]; then
-		continue
-	fi
-	if [[ "$INPUT" == $'\E' ]]; then
-		exit 0
-	fi
+sub write_registers($file) {
+    my $swap = "$file.tmp";
+    write_file($swap, map { "$_> $REGISTERS{$_}\n" } sort keys %REGISTERS);
+    rename($swap, $file) or die "Cannot rename '$swap' to '$file': $!\n";
+}
 
-	if [[ -n "${POINTS[$INPUT]}" ]]; then
-		echo -e "${BOLD}$ ${POINTS[$INPUT]}${RST}"
-		exec 1>&3
-		echo "${POINTS[$INPUT]}"
-		exit 0
-	fi
-done
+sub read_key() {
+    require Term::ReadKey;
+    Term::ReadKey::ReadMode('cbreak');
+
+    local $SIG{INT} = sub {
+        Term::ReadKey::ReadMode('restore');
+        print "\n";
+        exit 1;
+    };
+
+    my $key = Term::ReadKey::ReadKey(0);
+    Term::ReadKey::ReadMode('restore');
+    return $key;
+}
+
+sub main($config_file, $register_file) {
+    die "No config file specified.\n" unless $config_file;
+
+    read_config($config_file);
+    read_registers($register_file) if $register_file;
+
+    while (1) {
+        list_options();
+        print "${RED}> ${RST}";
+
+        my $input = read_key();
+        print "$input\n";
+
+        next unless defined $input;
+        $input =~ s/^\s+|\s+$//g;
+        next if $input eq '';
+
+        # ESC → clean exit
+        if (ord($input) == 27) {
+            exit 0;
+        }
+
+        my $cmd = '';
+        if (exists $QCKCMDS{$input}) {
+            $cmd = $QCKCMDS{$input};
+        }
+        elsif (exists $REGISTERS{$input}) {
+            $cmd = $REGISTERS{$input};
+        }
+
+        if ($cmd ne '') {
+            print "${BOLD}\$ $cmd${RST}\n";
+            open(STDOUT, '>&', $REAL_STDOUT) or die "Cannot restore STDOUT: $!";
+            print $cmd . "\n";
+            exit 0;
+        }
+    }
+}
+
+sub register_yank_mode($config_file, $register_file) {
+    die "No register file specified.\n" unless $register_file;
+
+    read_config($config_file);
+    read_registers($register_file);
+
+    list_options();
+    print "${MAGENTA}(${RST}choose-register${MAGENTA}) > ${RST}";
+    my $key = read_key();
+    return unless defined $key;
+    print "$key ";
+
+    if (defined $ENV{QCKCMD_REGISTER_YANK} && $ENV{QCKCMD_REGISTER_YANK} ne '') {
+        my $cmd = $ENV{QCKCMD_REGISTER_YANK};
+        $cmd =~ s/^\s+//;
+        $REGISTERS{$key} = $cmd;
+    } else {
+        delete $REGISTERS{$key};
+    }
+
+    write_registers($register_file);
+}
+
+# ---
+
+my %opts;
+getopts('hi:r:', \%opts) or do {
+    print STDERR "${RED}Unrecognized option, exiting...${RST}\n";
+    exit 1;
+};
+
+if ($opts{h}) {
+    usage();
+    exit 0;
+}
+
+my $config_file   = $opts{i} // '';
+my $register_file = $opts{r} // '';
+
+if (defined $ENV{QCKCMD_REGISTER_YANK_MODE}
+&&  $ENV{QCKCMD_REGISTER_YANK_MODE} ne '') {
+    register_yank_mode($config_file, $register_file);
+} else {
+    main($config_file, $register_file);
+}
